// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"oxylabs-homework/internal/adapters/quicserver/handlers"
	"oxylabs-homework/internal/drivers/wireproviders"
)

// Injectors from wire.go:

func initialize(outboundCh chan string, inboundCh <-chan string) (application, error) {
	options, err := wireproviders.NewOptions()
	if err != nil {
		return application{}, err
	}
	config, err := wireproviders.NewConfig(options)
	if err != nil {
		return application{}, err
	}
	loggerConfig := config.Logger
	zapConfig, err := wireproviders.NewLoggerConfig(loggerConfig)
	if err != nil {
		return application{}, err
	}
	logger, err := wireproviders.NewLoggerFromConfig(zapConfig)
	if err != nil {
		return application{}, err
	}
	serverConfig := config.Server
	publisherHandler := handlers.NewPublisherHandler(logger, outboundCh)
	tlsConfig := config.TLS
	config2, err := wireproviders.NewTLSConfig(tlsConfig)
	if err != nil {
		return application{}, err
	}
	publisherServer, err := wireproviders.NewPublisherQUICServerFromConfig(serverConfig, publisherHandler, config2)
	if err != nil {
		return application{}, err
	}
	subscriberHandler := handlers.NewSubscriberHandler(logger, inboundCh)
	subscriberServer, err := wireproviders.NewSubscriberQUICServerFromConfig(serverConfig, subscriberHandler, config2)
	if err != nil {
		return application{}, err
	}
	mainApplication := newApplication(logger, publisherServer, subscriberServer)
	return mainApplication, nil
}
